/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as ApiOcrRouteImport } from './routes/api/ocr'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AuthenticatedCardsIndexRouteImport } from './routes/_authenticated/cards/index'
import { Route as AuthenticatedCardsNewRouteImport } from './routes/_authenticated/cards/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedCardsIdIndexRouteImport } from './routes/_authenticated/cards/$id/index'
import { Route as AuthenticatedCardsIdEditRouteImport } from './routes/_authenticated/cards/$id/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiOcrRoute = ApiOcrRouteImport.update({
  id: '/api/ocr',
  path: '/api/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCardsIndexRoute = AuthenticatedCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCardsNewRoute = AuthenticatedCardsNewRouteImport.update({
  id: '/cards/new',
  path: '/cards/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCardsIdIndexRoute =
  AuthenticatedCardsIdIndexRouteImport.update({
    id: '/cards/$id/',
    path: '/cards/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCardsIdEditRoute =
  AuthenticatedCardsIdEditRouteImport.update({
    id: '/cards/$id/edit',
    path: '/cards/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/upload': typeof ApiUploadRoute
  '/cards/new': typeof AuthenticatedCardsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cards/': typeof AuthenticatedCardsIndexRoute
  '/cards/$id/edit': typeof AuthenticatedCardsIdEditRoute
  '/cards/$id/': typeof AuthenticatedCardsIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/upload': typeof ApiUploadRoute
  '/': typeof AuthenticatedIndexRoute
  '/cards/new': typeof AuthenticatedCardsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/cards': typeof AuthenticatedCardsIndexRoute
  '/cards/$id/edit': typeof AuthenticatedCardsIdEditRoute
  '/cards/$id': typeof AuthenticatedCardsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/api/ocr': typeof ApiOcrRoute
  '/api/upload': typeof ApiUploadRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cards/new': typeof AuthenticatedCardsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/cards/': typeof AuthenticatedCardsIndexRoute
  '/_authenticated/cards/$id/edit': typeof AuthenticatedCardsIdEditRoute
  '/_authenticated/cards/$id/': typeof AuthenticatedCardsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/categories'
    | '/api/ocr'
    | '/api/upload'
    | '/cards/new'
    | '/api/auth/$'
    | '/cards/'
    | '/cards/$id/edit'
    | '/cards/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/categories'
    | '/api/ocr'
    | '/api/upload'
    | '/'
    | '/cards/new'
    | '/api/auth/$'
    | '/cards'
    | '/cards/$id/edit'
    | '/cards/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/categories'
    | '/api/ocr'
    | '/api/upload'
    | '/_authenticated/'
    | '/_authenticated/cards/new'
    | '/api/auth/$'
    | '/_authenticated/cards/'
    | '/_authenticated/cards/$id/edit'
    | '/_authenticated/cards/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiOcrRoute: typeof ApiOcrRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/ocr': {
      id: '/api/ocr'
      path: '/api/ocr'
      fullPath: '/api/ocr'
      preLoaderRoute: typeof ApiOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cards/': {
      id: '/_authenticated/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof AuthenticatedCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cards/new': {
      id: '/_authenticated/cards/new'
      path: '/cards/new'
      fullPath: '/cards/new'
      preLoaderRoute: typeof AuthenticatedCardsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cards/$id/': {
      id: '/_authenticated/cards/$id/'
      path: '/cards/$id'
      fullPath: '/cards/$id/'
      preLoaderRoute: typeof AuthenticatedCardsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cards/$id/edit': {
      id: '/_authenticated/cards/$id/edit'
      path: '/cards/$id/edit'
      fullPath: '/cards/$id/edit'
      preLoaderRoute: typeof AuthenticatedCardsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCardsNewRoute: typeof AuthenticatedCardsNewRoute
  AuthenticatedCardsIndexRoute: typeof AuthenticatedCardsIndexRoute
  AuthenticatedCardsIdEditRoute: typeof AuthenticatedCardsIdEditRoute
  AuthenticatedCardsIdIndexRoute: typeof AuthenticatedCardsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCardsNewRoute: AuthenticatedCardsNewRoute,
  AuthenticatedCardsIndexRoute: AuthenticatedCardsIndexRoute,
  AuthenticatedCardsIdEditRoute: AuthenticatedCardsIdEditRoute,
  AuthenticatedCardsIdIndexRoute: AuthenticatedCardsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiOcrRoute: ApiOcrRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
